var $ = window.jQuery = require('jquery')
require('iframe-resizer/js/iframeResizer.contentWindow.js')
require('./vendor/modernizr')

$(document).ready(function () {
  $('form').on({
    'submit': handleSubmit,
    'ajax:beforeSend': handleBeforeSend
  })

  $('a').on({
    'submit': handleClick,
    'ajax:beforeSend': handleBeforeSend
  })

  detectMissingTranslations()

  function handleSubmit (event) {
    event.preventDefault()
    event.returnValue = false
    alert('This was a form submission')
  }

  function handleClick (event) {
    event.preventDefault()
    alert('This was a link click')
  }

  function handleBeforeSend (event) {
    xhr.abort()
  }

  function detectMissingTranslations () {
    var $message = $('.js-.e-guide__translation-missing')
    var $component = $('.js-.e-guide__component')
    var $missingTranslations = $('.translation_missing') // Class + element generated by Rails

    if ($missingTranslations.length > 0) {
      $message.removeClass('is-hidden')

      $missingTranslations.forEach(function (translation) {
        var string = $(translation).attr('title').replace('translation missing:', '')
        $(translation).css('border', '1px dashed green')
        $message.find('ul').append('<div>' + string + '</div>')
      })
    }
  }
})
