---

steps:
  - label: ":javascript:"
    command: ".buildkite/steps/javascript.sh"
    plugins:
      docker#v1.4.0:
        image: "node:10-slim"
    agents:
      queue: "$AGENT_QUEUE"
    timeout_in_minutes: 10
